### ISSUE TITLE
Failed to perform `ays init` in a vanilla js8 installation

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/jumpscale_core8#189]
Steps to reproduce
- I installed jumpscale in a fresh ubuntu 14.04.
- Added the following ays repo: https://github.com/gig-projects/playenv
```bash
root@jsdev:/tmp# js
Python 3.5.0+ (default, Oct 11 2015, 09:05:38)
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: j.do.pullGitRepo('https://github.com/gig-projects/playenv')
git clone https://github.com/gig-projects/playenv.git -> /opt/code/github/gig-projects/playenv
cd /opt/code/github/gig-projects;git -c http.sslVerify=false clone --depth=1  https://github.com/gig-projects/playenv.git /opt/code/github/gig-projects/playenv
E:/bin/sh: 1: cd: can't cd to /opt/code/github/gig-projects
E:Cloning into '/opt/code/github/gig-projects/playenv'...
Username for 'https://github.com': fastgeert
Password for 'https://fastgeert@github.com':
Out[1]: '/opt/code/github/gig-projects/playenv'
Do you really want to exit ([y]/n)?

root@jsdev:/tmp# cd /opt/code/github/gig-projects/playenv/ays_github

root@jsdev:/opt/code/github/gig-projects/playenv/ays_github# ays init
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 199, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/ays", line 41, in init
    j.atyourservice.init()
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice/AtYourServiceFactory.py", line 292, in init
    bp.loadrecipes()
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice/Blueprint.py", line 44, in loadrecipes
    j.atyourservice.getRecipe(name=blueaysname)
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice/AtYourServiceFactory.py", line 612, in getRecipe
    template = self.getTemplate(domain=domain,name=name, version=version, role=role)
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice/AtYourServiceFactory.py", line 596, in getTemplate
    return self.findTemplates(domain=domain, name=name, version=version, role=role, first=first)
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice/AtYourServiceFactory.py", line 473, in findTemplates
    for template in self.templates:
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice/AtYourServiceFactory.py", line 118, in templates
    self._doinit()
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice/AtYourServiceFactory.py", line 242, in _doinit
    opt = j.tools.path.get('/opt')
  File "/usr/local/lib/python3.5/dist-packages/JumpScale/__init__.py", line 66, in __getattr__
    obj0 = importlib.machinery.SourceFileLoader(classname,classfile).load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/jumpscale8//lib/JumpScale/tools/path/PathFactory.py", line 1, in <module>
    from path import path
ImportError: No module named 'path'
root@jsdev:/opt/code/github/gig-projects/playenv/ays_github#

```
-

**Comment by ahussein** [comment]
Also the click python library is missing
`root@vagrant-ubuntu-trusty-64:/home/vagrant# ays
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 5, in <module>
    import click
ImportError: No module named 'click'`

**Comment by zaibon** [comment]
See #197
