### ISSUE TITLE
Installing JS8 fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#208]
When installing JS8 on a new Ubuntu 15.10, following the [documentation](https://gig.gitbooks.io/jumpscale8/content/GettingStarted/Install.html), I get an error:

[Fri29 07:33] - ...lib/JumpScale/tools/actions/Action.py:743  - ERROR    -
*TRACEBACK*********************************************************************************

Traceback (most recent call last):
  File "/tmp/actions/localhost/build.py", line 66, in build
    self.start(name)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/apps/CuisineRedis.py", line 82, in start
    self.cuisine.processmanager.ensure(name="redis_%s" % name,cmd=cmd,env={},path='$binDir')
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/Cuisine2.py", line 216, in processmanager
    self._processmanager = ProcessManagerFactory(self).get()
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/ProcessManagerFactory.py", line 34, in get
    pm = self.get_prefered()
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/ProcessManagerFactory.py", line 19, in get_prefered
    if self.is_available( pm):
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/ProcessManagerFactory.py", line 24, in is_available
    return self.systemdOK()
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/ProcessManagerFactory.py", line 12, in systemdOK
    return not self.cuisine.core.isDocker and self.cuisine.core.command_check("systemctl")
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1167, in isDocker
    self._isDocker = self._cgroup.find("docker") != -1
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1162, in _cgroup
    self.__cgroup = self.file_read("/proc/1/cgroup")
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 474, in file_read
    return base64.b64decode(frame).decode()
  File "/usr/lib/python3.5/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
[Fri29 07:33] - ...lib/JumpScale/tools/actions/Action.py:749  - ERROR    -

******************************************************************************************

[Fri29 07:33] - ...lib/JumpScale/tools/actions/Action.py:621  - ERROR    - error in action: action: build                runid:localhost       (ERROR)

What to do?

**Comment by yveskerwyn** [comment]
Still not working...

      Running setup.py install for cryptography: started
        Running setup.py install for cryptography: finished with status 'error'
        Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-07mos8ny/cryptography/setup.py';exec(compile(getattr(tokenize, 'open',
        open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mjkqky3d-record/install-record.txt --single-version-externally-managed --compile:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-07mos8ny/cryptography/setup.py", line 335, in <module>
            **keywords_with_side_effects(sys.argv)
          File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
            _setup_distribution = dist = klass(attrs)
          File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 272, in __init__
            _Distribution.__init__(self,attrs)
          File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
            self.finalize_options()
          File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 327, in finalize_options
            ep.load()(self, ep.name, value)
          File "/usr/local/lib/python3.5/dist-packages/cffi/setuptools_ext.py", line 161, in cffi_modules
            add_cffi_module(dist, cffi_module)
          File "/usr/local/lib/python3.5/dist-packages/cffi/setuptools_ext.py", line 48, in add_cffi_module
            execfile(build_file_name, mod_vars)
          File "/usr/local/lib/python3.5/dist-packages/cffi/setuptools_ext.py", line 24, in execfile
            exec(code, glob, glob)
          File "src/_cffi_src/build_openssl.py", line 86, in <module>
            extra_link_args=extra_link_args(compiler_type()),
          File "/tmp/pip-build-07mos8ny/cryptography/src/_cffi_src/utils.py", line 64, in build_ffi_for_binding
            extra_link_args=extra_link_args,
          File "/tmp/pip-build-07mos8ny/cryptography/src/_cffi_src/utils.py", line 72, in build_ffi
            ffi = FFI()
          File "/usr/local/lib/python3.5/dist-packages/cffi/api.py", line 59, in __init__
            "version mismatch, %s != %s" % (backend.__version__, __version__)
        AssertionError: version mismatch, 1.1.2 != 1.6.0
        ----------------------------------------
      Rolling back uninstall of cryptography
    STDERR:
    The directory '/home/yves/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that
        directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/home/yves/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that
        directory. If executing pip with sudo, you may want sudo's -H flag.
    Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-07mos8ny/cryptography/setup.py';exec(compile(getattr(tokenize, 'open',
        open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mjkqky3d-record/install-record.txt --single-version-externally-managed --compile"
        failed with error code 1 in /tmp/pip-build-07mos8ny/cryptography/
[Tue03 12:14] - ...lib/JumpScale/tools/actions/Action.py:749  - ERROR    -

******************************************************************************************

[Tue03 12:14] - ...lib/JumpScale/tools/actions/Action.py:621  - ERROR    - error in action: action: run                  runid:localhost       (ERROR)
    pip3 install paramiko --upgrade

@maxux is looking into it...

**Comment by maxux** [comment]
Issue occures during setup of `paramiko` via pip.
Can't figure out now why it complains about `cryptography` version

**Comment by maxux** [comment]
Cannot reproduce on fresh ubuntu (server) 15.10
Setup script works fine.

**Comment by yveskerwyn** [comment]
@maxux I just tried it again on a fresh machine and got the same problem...

Maybe the problem is related to one of the following steps, in particular to the user I create first:

- ssh cloudscalers@...
- sudo vi /etc/hosts -> adding the name of the vm
- sudo adduser yves
- sudo adduser yves sudo -> in order to allow the new user (yves) to use sudo
- logout
- ssh yves@...
- mkdir ~/.ssh
- sudo vi ~/.ssh/authorized_keys -> add my public key
- logout
- login again with ssh yves@... in order to test access with my key
- follow installation [documentation](https://gig.gitbooks.io/jumpscale8/content/GettingStarted/Install.html), using sudo -s first

...

=> same error as before:

...

Running setup.py install for cryptography: started
        Running setup.py install for cryptography: finished with status 'error'
        Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l9upy4li/cryptography/setup.py';exec(compile(getattr(tokenize, 'open',
        open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xl8s09kt-record/install-record.txt --single-version-externally-managed --compile:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-l9upy4li/cryptography/setup.py", line 335, in <module>
            **keywords_with_side_effects(sys.argv)
          File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
            _setup_distribution = dist = klass(attrs)
          File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 272, in __init__
            _Distribution.__init__(self,attrs)
          File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
            self.finalize_options()
          File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 327, in finalize_options
            ep.load()(self, ep.name, value)
          File "/usr/local/lib/python3.5/dist-packages/cffi/setuptools_ext.py", line 161, in cffi_modules
            add_cffi_module(dist, cffi_module)
          File "/usr/local/lib/python3.5/dist-packages/cffi/setuptools_ext.py", line 48, in add_cffi_module
            execfile(build_file_name, mod_vars)
          File "/usr/local/lib/python3.5/dist-packages/cffi/setuptools_ext.py", line 24, in execfile
            exec(code, glob, glob)
          File "src/_cffi_src/build_openssl.py", line 93, in <module>
            extra_link_args=extra_link_args(compiler_type()),
          File "/tmp/pip-build-l9upy4li/cryptography/src/_cffi_src/utils.py", line 64, in build_ffi_for_binding
            extra_link_args=extra_link_args,
          File "/tmp/pip-build-l9upy4li/cryptography/src/_cffi_src/utils.py", line 72, in build_ffi
            ffi = FFI()
          File "/usr/local/lib/python3.5/dist-packages/cffi/api.py", line 59, in __init__
            "version mismatch, %s != %s" % (backend.__version__, __version__)
        AssertionError: version mismatch, 1.1.2 != 1.6.0
        ----------------------------------------
      Rolling back uninstall of cryptography
    STDERR:
    The directory '/home/yves/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that
        directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/home/yves/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that
        directory. If executing pip with sudo, you may want sudo's -H flag.
    Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l9upy4li/cryptography/setup.py';exec(compile(getattr(tokenize, 'open',
        open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xl8s09kt-record/install-record.txt --single-version-externally-managed --compile"
        failed with error code 1 in /tmp/pip-build-l9upy4li/cryptography/
[Wed04 18:38] - ...lib/JumpScale/tools/actions/Action.py:749  - ERROR    -

******************************************************************************************

[Wed04 18:38] - ...lib/JumpScale/tools/actions/Action.py:621  - ERROR    - error in action: action: run                  runid:localhost       (ERROR)
    pip3 install paramiko --upgrade

**Comment by maxux** [comment]
I can reproduce in a new vm in your cloudspace. I will investigate when possible.

**Comment by yveskerwyn** [comment]
I'm looking forward to your findings @maxux

**Comment by maxux** [comment]
Able to fix with:

- Go in root
`$ sudo -s`

- Fix vm hostname (if needed)
`# grep $(hostname) /etc/hosts || sed -i "s/.1 localhost/.1 localhost $(hostname)/g" /etc/hosts`

- Update vm at first
`# apt-get update && apt-get -y dist-upgrade`

- Add github to know hosts (avoid the "yes" to type manually during setup)
`ssh-keyscan github.com >> ~/.ssh/known_hosts`

- install jumpscale
`# cd /tmp;rm -f install.sh;curl -k https://raw.githubusercontent.com/Jumpscale/jumpscale_core8/master/install/install.sh > install.sh;bash install.sh`

Setup works fine with these steps. Documentation will be updated.

**Comment by yveskerwyn** [comment]
@maxux installation failed again, but when trying once more adding the -H option to sudo -s it all went fine :-)

so:
```shell
$ sudo -s -H
```

**Comment by maxux** [comment]
I updated my post and documentation :)
