### ISSUE TITLE
locale issue with AYS

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jumpscale_core8#219]
After installing js8 (installation went okay), running the ays command fails with the following error:

```
root@8d6d80fb257a:/# ays
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 198, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.5/dist-packages/click/_unicodefun.py", line 119, in _verify_python3_env
    'mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Either run this under Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

**Comment by rkhamis** [comment]
There's already a task for getting JS8 to run on 16.04 gig-projects/org_development#92

**Comment by abdulrahmantkhalifa** [comment]
i believe that setting the LC_ALL and the LANG are the system's responsibility , so if someone is not using the provided docker images to run jumpscale it his responsibilty to set the enviroment variables , and the error message is clear and provides a solution ,

**Comment by ahussein** [comment]
https://github.com/Jumpscale/jumpscale_core8/pull/311
