### ISSUE TITLE
Installing JS8 fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jumpscale_core8#253]
Installing JS8 fails on Ubuntu 16.04 with the following error:

```
[Tue31 10:57] - ...lib/JumpScale/tools/actions/Action.py:551  - INFO     -   * python              : 


*ERROR***********************************************************************************
action: python               runid:localhost            (ERROR)
    CuisineInstallerDevelop.python.|
    path: /opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineInstallerDevelop.py
ERROR:
    could not define osversion
[Tue31 10:57] - ...lib/JumpScale/tools/actions/Action.py:775  - ERROR    - 
*SOURCECODE******************************************************************************

from JumpScale import j

from ActionDecorator import ActionDecorator

from JumpScale import j
args="""
[]
"""
kwargs="""
{}
"""

def python(self):
    if self.cuisine.platformtype.osname == "debian":
        C = """
        libpython3.4-dev
        python3.4-dev
        """
    elif self.cuisine.platformtype.osname == 'ubuntu' and self.cuisine.platformtype.osversion == '16.04':
        C = """
        libpython3.5-dev
        python3.5-dev
        """
    else:
        C = """
        libpython3.4-dev
        python3.4-dev
        libpython3.5-dev
        python3.5-dev
        """
    self.cuisine.package.multiInstall(C)

    C="""
    libffi-dev
    gcc
    make
    build-essential
    autoconf
    libtool
    pkg-config
    libpq-dev
    libsqlite3-dev
    #net-tools
    """
    self.cuisine.package.multiInstall(C)
[Tue31 10:57] - ...lib/JumpScale/tools/actions/Action.py:788  - ERROR    - 
*TRACEBACK*********************************************************************************

Traceback (most recent call last):
  File "/tmp/actions/localhost/python.py", line 20, in python
    elif self.cuisine.platformtype.osname == 'ubuntu' and self.cuisine.platformtype.osversion == '16.04':
  File "/opt/jumpscale8//lib/JumpScale/core/main/PlatformTypes.py", line 139, in osversion
    raise j.exceptions.RuntimeError("could not define osversion")
OurExceptions.RuntimeError: ERROR: could not define osversion ((type:runtime.error)
[Tue31 10:57] - ...lib/JumpScale/tools/actions/Action.py:794  - ERROR    - 

******************************************************************************************

[Tue31 10:57] - ...lib/JumpScale/tools/actions/Action.py:666  - ERROR    - error in action: action: python               runid:localhost       (ERROR)
    

```

**Comment by ahussein** [comment]
https://github.com/Jumpscale/jumpscale_core8/pull/254

**Comment by ahussein** [comment]
will be fixed by https://github.com/Jumpscale/jumpscale_core8/pull/255
