### ISSUE TITLE
AYSRun tries to access None value.

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jumpscale_core8#358]
```
Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 338, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/jumpscale8/bin/ays", line 79, in init
    atyourservice.init(role=role, instance=instance, data=data)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice/AtYourServiceRepo.py", line 287, in init
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice/AYSRun.py", line 247, in execute
    step.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice/AYSRun.py", line 105, in execute
    stepaction.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice/AYSRun.py", line 62, in execute
    j.actions.last.print()
AttributeError: 'NoneType' object has no attribute 'print'
```

**Comment by rkhamis** [comment]
What were you trying to do to get this error?

**Comment by zaibon** [comment]
command that triggers that' was `ays init` on the cockpit blueprint
