### ISSUE TITLE
UnicodeDecodeError when executing ays blueprint

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#393]
Traceback (most recent call last):

  File "/opt/jumpscale8/bin/ays", line 339, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1057, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/jumpscale8/bin/ays", line 22, in cli
    atyourservice = j.atyourservice.get(j.sal.fs.getBaseName(cwd), cwd)
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice/AtYourServiceFactory.py", line 69, in get
    if name not in self.repos:
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice/AtYourServiceFactory.py", line 86, in repos
    self._repos[name] = AtYourServiceRepo(name, path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice/AtYourServiceRepo.py", line 45, in __init__
    self._load_blueprints()
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice/AtYourServiceRepo.py", line 225, in _load_blueprints
    self._blueprints[path] = Blueprint(self, path=path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice/Blueprint.py", line 23, in __init__
    self.content = j.sal.fs.fileGetContents(path)
  File "/opt/jumpscale8//lib/JumpScale/sal/fs/SystemFS.py", line 1317, in fileGetContents
    data = fp.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8d in position 16: ordinal not in range(128)

**Comment by rkhamis** [comment]
What was in the blueprint?

**Comment by yveskerwyn** [comment]
Not sure what the exact blueprint was, I only know that it was one for deploying a VDC.

I remember that you then solved a problem by removing a swap file of the blueprint, maybe that was the cause. Feel free to close @rkhamis
