### ISSUE TITLE
pytoml.core.TomlError when executing ays blueprint

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#553]
load dirs
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 546, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/click/core.py", line 86, in augment_usage_errors
    yield
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/ays", line 171, in blueprint
    repo = j.atyourservice.get()
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice81/AtYourServiceFactory.py", line 343, in get
    return self.repoGet(path=path)
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice81/AtYourServiceFactory.py", line 351, in repoGet
    self._doinit()
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice81/AtYourServiceFactory.py", line 99, in _doinit
    global_templates_repos = j.atyourservice.config['metadata']
  File "/opt/jumpscale8//lib/JumpScale/baselib/atyourservice81/AtYourServiceFactory.py", line 59, in config
    cfg = j.data.serializer.toml.load(config_path)
  File "/opt/jumpscale8/lib/JumpScale/data/serializers/SerializerBase.py", line 12, in load
    return self.loads(b)
  File "/opt/jumpscale8//lib/JumpScale/data/serializers/SerializerTOML.py", line 18, in loads
    return pytoml.loads(s)
  File "/usr/local/lib/python3.5/dist-packages/pytoml/parser.py", line 23, in loads
    ast = _p_toml(src)
  File "/usr/local/lib/python3.5/dist-packages/pytoml/parser.py", line 344, in _p_toml
    s.expect_eof()
  File "/usr/local/lib/python3.5/dist-packages/pytoml/parser.py", line 124, in expect_eof
    return self._expect(self.consume_eof())
  File "/usr/local/lib/python3.5/dist-packages/pytoml/parser.py", line 164, in _expect
    raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
pytoml.core.TomlError: <string>(13, 9): msg

**Comment by rkhamis** [comment]
Fixed.
