### ISSUE TITLE
"ays create_repo" and "ays blueprint" fails because of missing VARDIR directory

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#568]
Traceback:

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/jumpscale8//lib/JumpScale/data/idgenerator/IDGenerator.py", line 2, in <module>
    from JumpScale import j
  File "/opt/jumpscale8//lib/JumpScale/__init__.py", line 207, in <module>
    j.application.init()
  File "/opt/jumpscale8//lib/JumpScale/core/main/Application.py", line 124, in init
    j.dirs.init()
  File "/opt/jumpscale8//lib/JumpScale/core/main/Dirs.py", line 56, in init
    self.varDir = self.normalize(j.do.VARDIR)
  File "/opt/jumpscale8/lib/JumpScale/InstallTools.py", line 565, in VARDIR
    return self.config["dirs"]["VARDIR"]
KeyError: 'VARDIR'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 7, in <module>
    from JumpScale import j
  File "/opt/jumpscale8/lib/JumpScale/__init__.py", line 207, in <module>
    j.application.init()
  File "/opt/jumpscale8//lib/JumpScale/core/main/Application.py", line 124, in init
    j.dirs.init()
  File "/opt/jumpscale8//lib/JumpScale/core/main/Dirs.py", line 56, in init
    self.varDir = self.normalize(j.do.VARDIR)
  File "/opt/jumpscale8/lib/JumpScale/InstallTools.py", line 565, in VARDIR
    return self.config["dirs"]["VARDIR"]
KeyError: 'VARDIR'
```

**Comment by yveskerwyn** [comment]
Adding "VARDIR: /optvar" to /optvar/cfg/jumpscale/system.yaml solved to problem
