### ISSUE TITLE
mvp-cockpit: ays update -n vdc fails

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#573]
Problem is specific to the situation of following Cockpit repo:
https://uk-g8-1.demo.greenitglobe.com/grid/job?id=99cbb986cb51ad0f7ddbea1a966b02289143f032

Updating the vdc actor failed because there is an existing **vdc4yves02** instance that didn't get installed because of issue [#76](https://github.com/Jumpscale/ays_jumpscale8/issues/76)... a problem that was supposed to get solved by updating the actor... a chicken and egg problem :-)

Here's the traceback:
```
root@vm-3856:/optvar/cockpit_repos/yves02# ays update -n vdc
/opt/jumpscale8/lib/JumpScale/data/capnp/ModelBase.py:67: UserWarning: This message has already been written once. Be very careful that you're not setting Text/Struct/List fields more than once, since that will cause memory leaks (both in memory and in the serialized data). You can disable this warning by setting the `_is_written` field of this object to False after every write.
  buff = self.dbobj.to_bytes()
/opt/jumpscale8/lib/JumpScale/data/capnp/ModelBase.py:67: UserWarning: This message has already been written once. Be very careful that you're not setting Text/Struct/List fields more than once, since that will cause memory leaks (both in memory and in the serialized data). You can disable this warning by setting the `_is_written` field of this object to False after every write.
  buff = self.dbobj.to_bytes()
Error of job: vdc!vdc4yves02 (processChange):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Job.py", line 167, in executeInProcess
    res = self.method(job=self)
  File "/tmp/actions/vdc/processChange.py", line 30, in action
    create=False)
  File "/opt/jumpscale8//lib/JumpScale/clients/openvcloud/Client.py", line 207, in space_get
    "Could not find space with name %s" % name)
JSExceptions.RuntimeError: ERROR: Could not find space with name vdc4yves02 ((type:runtime.error)


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 490, in <module>
    cli()
  File "/opt/jumpscale8/bin/ays", line 118, in update
    actor._initFromTemplate(template)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 107, in _initFromTemplate
    self.processChange("dataschema")
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 358, in processChange
    service.processChange(actor=self, changeCategory=changeCategory)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 507, in processChange
    args = job.executeInProcess()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Job.py", line 177, in executeInProcess
    raise j.exceptions.RuntimeError("could not execute job:%s" % self)
JSExceptions.RuntimeError: ERROR: could not execute job:job: vdc!vdc4yves02 (processChange) ((type:runtime.error)
```

**Comment by rkhamis** [comment]
fixed in https://github.com/Jumpscale/ays_jumpscale8/commit/73030902bbe46deca2c168b7ef581a6f33cdabee
