### ISSUE TITLE
mvp-cockpit: ays update => redis.exceptions.ResponseError

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#599]
Error when trying to update the node.ovc actor template using ```ays update -n node.ovc```

Using the Artilium Cockpit: https://gig.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=3856

```
root@vm-3856:/optvar/cockpit_repos/yves06# ays update -n node.ovc
Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 490, in <module>
    cli()
  File "/opt/jumpscale8//lib/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/jumpscale8//lib/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/jumpscale8//lib/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/jumpscale8//lib/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/jumpscale8//lib/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/jumpscale8/bin/ays", line 118, in update
    actor._initFromTemplate(template)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 101, in _initFromTemplate
    self._processActionsFile(j.sal.fs.joinPaths(template.path, "actions.py"))
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 204, in _processActionsFile
    self._addAction(actionName, amSource, amDecorator, amMethodArgs, amDoc)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 308, in _addAction
    self._addAction2(actionName, ac)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 317, in _addAction2
    self.processChange("action_new_%s" % actionName)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 355, in processChange
    self.saveAll()
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 78, in saveAll
    self.model.save()
  File "/opt/jumpscale8/lib/JumpScale/data/capnp/ModelBase.py", line 70, in save
    self._db.set(self.key, buff)
  File "/opt/jumpscale8//lib/JumpScale/servers/key_value_store/store.py", line 221, in set
    self._set(key, data)
  File "/opt/jumpscale8//lib/JumpScale/servers/key_value_store/redis_store.py", line 32, in _set
    return self.redisclient.set(self._getKey(key), val, ex=expire)
  File "/opt/jumpscale8/lib/redis/client.py", line 1072, in set
    return self.execute_command('SET', *pieces)
  File "/opt/jumpscale8/lib/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/jumpscale8/lib/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/opt/jumpscale8/lib/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: OOM command not allowed when used memory > 'maxmemory'.
```

**Comment by yveskerwyn** [comment]
Quick fixed:
```
redis-cli -s /optvar/tmp/redis.sock
> config set maxmemory 3000000
````

**Comment by john-kheir** [comment]
## Environment 
Verified on gig
## Version 
8.1.0 rc1
