### ISSUE TITLE
mvp-cockpit: ays blueprint => capnperror

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#600]
Context: Cockpit repository "yves06" on the [Artilium Cockpit]( https://gig.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=3856)

Something wrong in my blueprint?

Stack trace:

```
root@vm-3856:/optvar/cockpit_repos/yves06# ays blueprint
/opt/jumpscale8/lib/JumpScale/data/capnp/ModelBase.py:67: UserWarning: This message has already been written once. Be very careful that you're not setting Text/Struct/List fields more than once, since that will cause memory leaks (both in memory and in the serialized data). You can disable this warning by setting the `_is_written` field of this object to False after every write.
  buff = self.dbobj.to_bytes()
cannot create data for schema from arguments, value type mismatch.
arguments:
{
 "bootdiskSize":10,
 "description":"",
 "disk":[

 ],
 "ipPrivate":"",
 "ipPublic":"",
 "machineId":0,
 "memory":2,
 "osImage":"Ubuntu 16.04 x64",
 "ovfCallbackUrl":"",
 "ovfLink":"",
 "ovfPassword":"",
 "ovfPath":"",
 "ovfUsername":"",
 "ports":[
  427342
 ],
 "sshAddr":"",
 "sshLogin":"",
 "sshPassword":"",
 "sshPort":0,
 "sshkey":"",
 "vdc":"vdc4js8"
}
schema:

@0xb7289a47d6f28893;
struct Schema {
	description @0 :Text;
	bootdiskSize @1 :Int32;
	memory @2 :Int32;
	osImage @3 :Text;
	ports @4 :List(Text);
	machineId @5 :Int32;
	ipPublic @6 :Text;
	ipPrivate @7 :Text;
	sshLogin @8 :Text;
	sshPassword @9 :Text;
	vdc @10 :Text;
	disk @11 :List(Text);
	sshkey @12 :Text;
	sshAddr @13 :Text;
	sshPort @14 :Int32;
	ovfLink @15 :Text;
	ovfUsername @16 :Text;
	ovfPassword @17 :Text;
	ovfPath @18 :Text;
	ovfCallbackUrl @19 :Text;

}
capnperror: expected reader.type == TEXT; Value type mismatch.


**** TRACEBACK ***
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/data/capnp/Capnp.py", line 67, in getObj
    configdata = schema.new_message(**args)
  File "capnp/lib/capnp.pyx", line 3045, in capnp.lib.capnp._StructModule.new_message (capnp/lib/capnp.cpp:63205)
  File "capnp/lib/capnp.pyx", line 2855, in capnp.lib.capnp._new_message (capnp/lib/capnp.cpp:60658)
  File "capnp/lib/capnp.pyx", line 1432, in capnp.lib.capnp._DynamicStructBuilder.from_dict (capnp/lib/capnp.cpp:30941)
  File "capnp/lib/capnp.pyx", line 1426, in capnp.lib.capnp._DynamicStructBuilder.from_dict (capnp/lib/capnp.cpp:30838)
  File "capnp/lib/capnp.pyx", line 1245, in capnp.lib.capnp._DynamicStructBuilder._set (capnp/lib/capnp.cpp:27574)
  File "capnp/lib/capnp.pyx", line 720, in capnp.lib.capnp._setDynamicField (capnp/lib/capnp.cpp:17387)
  File "capnp/lib/capnp.pyx", line 903, in capnp.lib.capnp._from_list (capnp/lib/capnp.cpp:20952)
  File "capnp/lib/capnp.pyx", line 504, in capnp.lib.capnp._DynamicListBuilder._set (capnp/lib/capnp.cpp:13140)
  File "capnp/lib/capnp.pyx", line 707, in capnp.lib.capnp._setDynamicField (capnp/lib/capnp.cpp:16334)
capnp.lib.capnp.KjException: src/capnp/dynamic.c++:1713: failed: expected reader.type == TEXT; Value type mismatch.
stack: 0x7f8503b1bb09 0x7f8503b1f73d 0x7f8503af5a2c 0x7f8503ae9273 0x7f8503af4668 0x7f85039f05f0 0x7f85039f2e8b 0x7f8503951a08 0x7f85039ed71e 0x7f85039efaf5 0x7f850396ce48 0x7f8503967d74 0x7f850398239b 0x7f85039826d2 0x4e1757 0x5bcf47

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 490, in <module>
    cli()
  File "/opt/jumpscale8/bin/ays", line 137, in blueprint
    repo.blueprintExecute(role=role, instance=instance, path=path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 320, in blueprintExecute
    bp.load(role=role, instance=instance)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Blueprint.py", line 181, in load
    actor.serviceCreate(instance=bpinstance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 378, in serviceCreate
    service = Service(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 22, in __init__
    self._initFromActor(actor, args=args, name=name)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 87, in _initFromActor
    dbobj.data = j.data.capnp.getBinaryData(j.data.capnp.getObj(dbobj.dataSchema, args=args))
  File "/opt/jumpscale8//lib/JumpScale/data/capnp/Capnp.py", line 86, in getObj
    raise j.exceptions.Input(message=msg, level=1, source="", tags="", msgpub="")
JSExceptions.Input: ERROR: cannot create data for schema from arguments, value type mismatch.
arguments:
{
 "bootdiskSize":10,
 "description":"",
 "disk":[

 ],
 "ipPrivate":"",
 "ipPublic":"",
 "machineId":0,
 "memory":2,
 "osImage":"Ubuntu 16.04 x64",
 "ovfCallbackUrl":"",
 "ovfLink":"",
 "ovfPassword":"",
 "ovfPath":"",
 "ovfUsername":"",
 "ports":[
  427342
 ],
 "sshAddr":"",
 "sshLogin":"",
 "sshPassword":"",
 "sshPort":0,
 "sshkey":"",
 "vdc":"vdc4js8"
}
schema:

@0xb7289a47d6f28893;
struct Schema {
	description @0 :Text;
	bootdiskSize @1 :Int32;
	memory @2 :Int32;
	osImage @3 :Text;
	ports @4 :List(Text);
	machineId @5 :Int32;
	ipPublic @6 :Text;
	ipPrivate @7 :Text;
	sshLogin @8 :Text;
	sshPassword @9 :Text;
	vdc @10 :Text;
	disk @11 :List(Text);
	sshkey @12 :Text;
	sshAddr @13 :Text;
	sshPort @14 :Int32;
	ovfLink @15 :Text;
	ovfUsername @16 :Text;
	ovfPassword @17 :Text;
	ovfPath @18 :Text;
	ovfCallbackUrl @19 :Text;

}
capnperror: expected reader.type == TEXT; Value type mismatch.
 ((type:input.error)
```

**Comment by rkhamis** [comment]
The message says there's a type error
Check your ports. They should be strings.
