### ISSUE TITLE
mvp-cockpit: python3.5: can't open file 'api_server': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_core8#608]
When installing Cockpit for CentriLogic, failing on step 8:

```
Error of job: ayscockpit!main (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/ayscockpit/install.py", line 58, in action
    pm.ensure(cmd=cmd, name='cockpit_api_%s' % service.name, path=cuisine.core.args_replace('$appDir/ays_api'))
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineProcessManager.py", line 275, in ensure
    self._cuisine.tmux.executeInScreen("main", name, cmd)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineTmux.py", line 179, in executeInScreen
    rc, out = checkOutput(die)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineTmux.py", line 164, in checkOutput
    raise j.exceptions.RuntimeError(msg)
JSExceptions.RuntimeError: ERROR: Could not execute cmd:cd /opt/jumpscale8/apps/ays_api && jspython api_server
Out/Err:
python3.5: can't open file 'api_server': [Errno 2] No such file or directory

 ((type:runtime.error)
```

******************************************************************************************

**Comment by yveskerwyn** [comment]
moved to [#288](https://github.com/Jumpscale/jscockpit/issues/288)
