### ISSUE TITLE
Jumpscale fail to install

### ISSUE THREAD

**Issue by khaledkbadr** [Jumpscale/jumpscale_core8#668]
It appear that `Jumpscale` try to clone the `git` repo using `ssh` not `https`

```
pull:https://github.com/Jumpscale/jumpscale_core8.git ->/opt/code/github/jumpscale/jumpscale_core8
git pull https://github.com/Jumpscale/jumpscale_core8.git -> /opt/code/github/jumpscale/jumpscale_core8
cd /opt/code/github/jumpscale/jumpscale_core8;git -c http.sslVerify=false pull origin 8.1.0
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "bootstrap.py", line 50, in <module>
    do.installer.installJS()
  File "/tmp/InstallTools.py", line 108, in installJS
    self.do.pullGitRepo(args2['JSGIT'], branch=args2['JSBRANCH'], ssh="first")
  File "/tmp/InstallTools.py", line 2530, in pullGitRepo
    self.execute(cmd, timeout=600, executor=executor)
  File "/tmp/InstallTools.py", line 1871, in execute
    raise RuntimeError("Could not execute cmd:\n'%s'\nerr:\n%s" % (command, err))
RuntimeError: Could not execute cmd:
'cd /opt/code/github/jumpscale/jumpscale_core8;git -c http.sslVerify=false pull origin 8.1.0'
err:
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

root@61c97e09bf34:/tmp# js
```

**Comment by despiegk** [comment]
It says pull https
