### ISSUE TITLE
need to flush database after ays destroy

### ISSUE THREAD

**Issue by xmonader** [Jumpscale/jumpscale_core8#697]
after doing `ays destroy` in a repo. I need to do `j.core.db.flushall()` to fix this error

```
root@vm-114:/opt/testevents# ays blueprint

**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 538, in <module>
    cli()
  File "/usr/local/bin/ays", line 137, in blueprint
    repo.blueprintExecute(role=role, instance=instance, path=path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 343, in blueprintExecute
    bp.load(role=role, instance=instance)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Blueprint.py", line 63, in load
    self._validate_models_data()
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Blueprint.py", line 293, in _validate_models_data
    actor = self.aysrepo.actorGet(name=actorname)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 92, in actorGet
    actor_models = self.db.actors.find(name=name)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/models/ActorsCollection.py", line 76, in find
    res.append(self.get(key))
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/models/ActorsCollection.py", line 46, in get
    new=False)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/models/ActorServiceBaseModel.py", line 16, in __init__
    super().__init__(capnp_schema=capnp_schema, category=category, db=db, index=index, key=key, new=new)
  File "/opt/jumpscale8/lib/JumpScale/data/capnp/ModelBase.py", line 145, in __init__
    super().__init__(capnp_schema=capnp_schema, category=category, db=db, index=index, key=key, new=new)
  File "/opt/jumpscale8/lib/JumpScale/data/capnp/ModelBase.py", line 35, in __init__
    self._category, key), level=1, source="", tags="", msgpub="")
JSExceptions.Input: ERROR: Cannot find object:Actor!8725c6099b20ac821bb88c303c499fb2 ((type:input.error)
root@vm-114:/opt/testevents# ays destroy
root@vm-114:/opt/testevents# js
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: j.core.db.flushall()
Out[1]: True

In [2]: exit

root@vm-114:/opt/testevents# ays blueprint
[Mon09 10:17] - ...le/baselib/atyourservice81/Service.py:45   - INFO     - init service p1 from actproducer
[Mon09 10:17] - ...le/baselib/atyourservice81/Service.py:45   - INFO     - init service c1 from actconsumer
[Mon09 10:17] - .../atyourservice81/AtYourServiceRepo.py:458  - INFO     - init service: service:actconsumer!c1
[Mon09 10:17] - .../atyourservice81/AtYourServiceRepo.py:458  - INFO     - init service: service:actproducer!p1
init done
blueprint done

```

**Comment by zaibon** [comment]
To be validated, but I think I fixed this in https://github.com/Jumpscale/jumpscale_core8/commit/bd051ef7fa6d3351024c050f5273660537ae0a60
