### ISSUE TITLE
Cannot acquire lock during the installation of s3 

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/jumpscale_core8#713]
Cannot acquire lock during the installation of g8osfs instance while running blueprint of s3 

```
Error of job: app_docker!docker (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/app_docker/install.py", line 8, in action
    cuisine.systemservices.docker.install()
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/systemservices/CuisineDocker.py", line 35, in install
    with FileLock(LOCK_NAME, locktimeout=LOCK_TIMEOUT):
  File "/opt/jumpscale8/lib/JumpScale/sal/fs/SystemFS.py", line 216, in __enter__
    lock(self.lock_name, reentry=self.reentry, locktimeout=self.locktimeout)
  File "/opt/jumpscale8/lib/JumpScale/sal/fs/SystemFS.py", line 82, in lock
    message="Cannot acquire lock [%s]" % (lockname))
JumpScale.sal.fs.SystemFS.LockTimeoutException: Cannot acquire lock [APT-LOCK]


******************************************************************************************

Error of job: fs.g8osfs!fuse (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/fs.g8osfs/install.py", line 6, in action
    cuisine.package.mdupdate()
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisinePackage.py", line 52, in mdupdate
    with FileLock(LOCK_NAME, locktimeout=LOCK_TIMEOUT):
  File "/opt/jumpscale8/lib/JumpScale/sal/fs/SystemFS.py", line 216, in __enter__
    lock(self.lock_name, reentry=self.reentry, locktimeout=self.locktimeout)
  File "/opt/jumpscale8/lib/JumpScale/sal/fs/SystemFS.py", line 82, in lock
    message="Cannot acquire lock [%s]" % (lockname))
JumpScale.sal.fs.SystemFS.LockTimeoutException: Cannot acquire lock [APT-LOCK]


******************************************************************************************
```
## blueprint 
g8client__main:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'admin'
    password: 'KrOe6gE9K5nCQdmretfXnj'
    account: 'newacc'

vdc__main3s3:
    g8client: 'main'
    location: 'du-conv-2'

disk.ovc__disk1:
   size: 1000

s3__s3vm:
    vdc: 'main3s3'
    disk:
      - 'disk1'
    hostprefix: 's3app22'

test_s3__ts:
    s3: 's3vm'
    scality: 'app'

actions:
    - action: 'test'
      actor: 'test_s3'

**Comment by rkhamis** [comment]
Please validate on 8.2.0
