### ISSUE TITLE
Error during the installation of jumpscale

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/jumpscale_core8#723]
```Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-y5jrgd_6/pycapnp/setup.py", line 176, in <module>
      'Topic :: Communications'],
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-y5jrgd_6/pycapnp/setup.py", line 120, in run
      build_libcapnp(bundle_dir, build_dir)
    File "/tmp/pip-build-y5jrgd_6/pycapnp/buildutils/build.py", line 30, in build_libcapnp
      raise RuntimeError('Make failed')
  RuntimeError: Make failed
  
  ----------------------------------------
  **Failed building wheel for pycapnp**
  Running setup.py clean for pycapnp
Failed to build pycapnp
Installing collected packages: pycapnp
  Running setup.py install for pycapnp ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-y5jrgd_6/pycapnp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wlz6l6ry-record/install-record.txt --single-version-externally-managed --compile:
    Compiling capnp/lib/capnp.pyx because it changed.
    [1/1] Cythonizing capnp/lib/capnp.pyx
    running install
    running build
    running build_py
    Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
    Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/capnp
    copying capnp/_gen.py -> build/lib.linux-x86_64-3.5/capnp
    copying capnp/version.py -> build/lib.linux-x86_64-3.5/capnp
    copying capnp/__init__.py -> build/lib.linux-x86_64-3.5/capnp
    copying capnp/__init__.pxd -> build/lib.linux-x86_64-3.5/capnp
    copying capnp/schema.capnp -> build/lib.linux-x86_64-3.5/capnp
    copying capnp/c++.capnp -> build/lib.linux-x86_64-3.5/capnp
    creating build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/non_circular.pxd -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/helpers.pxd -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/__init__.pxd -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/capabilityHelper.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/asyncHelper.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/checkCompiler.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/fixMaybe.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/rpcHelper.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    copying capnp/helpers/serialize.h -> build/lib.linux-x86_64-3.5/capnp/helpers
    creating build/lib.linux-x86_64-3.5/capnp/includes
    copying capnp/includes/types.pxd -> build/lib.linux-x86_64-3.5/capnp/includes
    copying capnp/includes/schema_cpp.pxd -> build/lib.linux-x86_64-3.5/capnp/includes
    copying capnp/includes/__init__.pxd -> build/lib.linux-x86_64-3.5/capnp/includes
    copying capnp/includes/capnp_cpp.pxd -> build/lib.linux-x86_64-3.5/capnp/includes
    creating build/lib.linux-x86_64-3.5/capnp/lib
    copying capnp/lib/capnp.pxd -> build/lib.linux-x86_64-3.5/capnp/lib
    copying capnp/lib/__init__.pxd -> build/lib.linux-x86_64-3.5/capnp/lib
    copying capnp/lib/pickle_helper.py -> build/lib.linux-x86_64-3.5/capnp/lib
    copying capnp/lib/__init__.py -> build/lib.linux-x86_64-3.5/capnp/lib
    copying capnp/lib/capnp.pyx -> build/lib.linux-x86_64-3.5/capnp/lib
    creating build/lib.linux-x86_64-3.5/capnp/templates
    copying capnp/templates/setup.py.tmpl -> build/lib.linux-x86_64-3.5/capnp/templates
    copying capnp/templates/module.pyx -> build/lib.linux-x86_64-3.5/capnp/templates
    running build_ext
    creating /tmp/tmpqfhddcch/tmp
    cc -c /tmp/timer_createtzu58kij.c -o /tmp/tmpqfhddcch/tmp/timer_createtzu58kij.o
    /tmp/timer_createtzu58kij.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^
    /tmp/timer_createtzu58kij.c: In function ‘main’:
    /tmp/timer_createtzu58kij.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
         timer_create();
         ^
    cc /tmp/tmpqfhddcch/tmp/timer_createtzu58kij.o -o /tmp/tmpqfhddcch/a.out
    /tmp/tmpqfhddcch/tmp/timer_createtzu58kij.o: In function `main':
    timer_createtzu58kij.c:(.text+0x15): undefined reference to `timer_create'
    collect2: error: ld returned 1 exit status
    creating tmp/tmpqfhddcch
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -c /tmp/tmpqfhddcch/vers.cpp -o tmp/tmpqfhddcch/vers.o --std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /tmp/tmpqfhddcch/vers.cpp:4:26: fatal error: capnp/common.h: No such file or directory
    compilation terminated.
    *WARNING* no libcapnp detected. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
    already have /tmp/pip-build-y5jrgd_6/pycapnp/bundled/capnproto-c++
    g++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    make: *** [src/capnp/compiler/compiler.lo] Error 1
    make: *** Waiting for unfinished jobs....
    g++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    make: *** [src/capnp/compiler/parser.lo] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-y5jrgd_6/pycapnp/setup.py", line 176, in <module>
        'Topic :: Communications'],
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-y5jrgd_6/pycapnp/setup.py", line 120, in run
        build_libcapnp(bundle_dir, build_dir)
      File "/tmp/pip-build-y5jrgd_6/pycapnp/buildutils/build.py", line 30, in build_libcapnp
        raise RuntimeError('Make failed')
    RuntimeError: Make failed
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-y5jrgd_6/pycapnp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wlz6l6ry-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-y5jrgd_6/pycapnp/
Traceback (most recent call last):
  File "bootstrap.py", line 49, in <module>
    do.installer.prepare()
  File "/tmp/InstallTools.py", line 488, in prepare
    self.do.dependencies.all()
  File "/tmp/dependencies.py", line 31, in all
    self.do.pip(C, executor=executor)
  File "/tmp/InstallTools.py", line 1197, in pip
    self.executeInteractive(cmd)
  File "/tmp/InstallTools.py", line 1880, in executeInteractive
    raise RuntimeError("Could not execute %s" % command)
RuntimeError: Could not execute pip3 install pycapnp --upgrade
```

**Comment by john-kheir** [comment]
with branches 8.1.0 and 8.1.1

**Comment by rkhamis** [comment]
@john-kheir I just did a clean installation and it works. Can you describe how you produced this?

**Comment by john-kheir** [comment]
I went through these steps on a 16.04 vm this morning and same issue occurred with me (on 8.1.0 as well)
![js8in](https://cloud.githubusercontent.com/assets/15011431/22193816/dcd1e95c-e146-11e6-9869-0a5725869362.png)

**Comment by john-kheir** [comment]
The VM i used was 512M memory .. so most probably that was the reason
