### ISSUE TITLE
AYS: ays destroy failed

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jumpscale_core8#744]
While trying to execute ays destroy on a repo. the command failed with the following error:
```
root@vm-9140:/tmp/test_repo# ays destroy

**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 538, in <module>
    cli()
  File "/usr/local/bin/ays", line 322, in destroy
    repo.destroy()
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 68, in destroy
    jobs.add(jc.getIndexFromKey(job_key))
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/models/JobsCollections.py", line 81, in getIndexFromKey
    ind = "%s:%s:%s:%s:%s:%s" % (job.dbobj.actorName, job.dbobj.serviceName,
AttributeError: 'NoneType' object has no attribute 'dbobj'
```

ays_jumpscale8 branch: 8.1.1
jumpscale_core branch: 8.1.1

**Comment by ahussein** [comment]
https://github.com/Jumpscale/jumpscale_core8/pull/745
