### ISSUE TITLE
Installing js8 fails using branch 8.2.0

### ISSUE THREAD

**Issue by ahussein** [Jumpscale/jumpscale_core8#753]
Failure with error
```
bootstrap installtools in dir /tmp and use branch:'8.2.0'
Traceback (most recent call last):
  File "bootstrap.py", line 37, in <module>
    InstallTools = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/InstallTools.py", line 31, in <module>
    from colorlog import ColoredFormatter
ImportError: No module named 'colorlog'
```
The colorlog lib is included in the dependences but it is used before installing it on the module level of the InstallTools module.

**Comment by ahussein** [comment]
using the install.sh on branch 8.2.0 fixes the problem.
