### ISSUE TITLE
Ays start command fails

### ISSUE THREAD

**Issue by khaledkbadr** [Jumpscale/jumpscale_core8#789]
```
***ERROR***
  type/level: runtime.error/1
Could not execute cmd:cd /opt/code/github/jumpscale/jumpscale_core8/apps/atyourservice;jspython main.py --host 127.0.0.1 --port 5000
Out/Err:
to see api:http://localhost:5000/

**** TRACEBACK ***
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click/_unicodefun.py", line 118,
in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured
 to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/p
ython3/for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/click/_unicodefun.py", line 118,
in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured
 to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/p
ython3/for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8


*

```

**Comment by zaibon** [comment]
This is a problem in your dev environement, not AYS

**Comment by khaledkbadr** [comment]
I know, It's a clean docker container and freshly installed Jumpscale. Shouldn't we handle this ourselves?

**Comment by rkhamis** [comment]
While it IS a problem with the env, ensuring locale is set properly is only smart. Will keep.

**Comment by zaibon** [comment]
don't we do that during jumpscale install ? I think that's where it should happens
