### ISSUE TITLE
Install script should not throw an error if repo already exists and up to date.

### ISSUE THREAD

**Issue by nbabenko** [Jumpscale/jumpscale_core8#796]
Install script should not throw an error if jumpscale_core repo already exists and up to date.

Place 1:
```
[Wed29 11:20] - InstallTools.py     :2061:installtools                   - INFO     - pull core
[Wed29 11:20] - InstallTools.py     :645 :installtools                   - INFO     - None:pull:git@github.com:Jumpscale/jumpscale_core8.git ->/opt/code/github/jumpscale/jumpscale_core8
[Wed29 11:20] - InstallTools.py     :683 :installtools                   - INFO     - git pull git@github.com:Jumpscale/jumpscale_core8.git -> /opt/code/github/jumpscale/jumpscale_core8
[Wed29 11:20] - InstallTools.py     :688 :installtools                   - INFO     - cd /opt/code/github/jumpscale/jumpscale_core8;git pull origin 8.2.0
Enter passphrase for key '/root/.ssh/id_rsa': 
E:From github.com:Jumpscale/jumpscale_core8
E:* branch            8.2.0      -> FETCH_HEAD
Already up-to-date.
--- Logging error ---
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/tmp/InstallTools.py", line 49, in format
    return super(LimitFormater, self).format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/site-packages/colorlog/colorlog.py", line 129, in format
    message = super(ColoredFormatter, self).format(record)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "bootstrap.py", line 55, in <module>
    do.installer.installJS()
  File "/tmp/InstallTools.py", line 2083, in installJS
    self.do.symlinkFilesInDir(src, dest, includeDirs=True)
  File "/tmp/InstallTools.py", line 1171, in symlinkFilesInDir
    items = self.listFilesAndDirsInDir(src, recursive=False, followSymlinks=False, listSymlinks=False)
  File "/tmp/InstallTools.py", line 1365, in listFilesAndDirsInDir
    self.logger.info('List files in directory with path: %s' % path, 9)
Message: 'List files in directory with path: /opt/code/github/jumpscale/jumpscale_core8/lib/JumpScale'
Arguments: (9,)
[Wed29 11:21] - InstallTools.py     :1177:installtools                   - INFO     - link /opt/code/github/jumpscale/jumpscale_core8/lib/JumpScale/__init__.py:/opt/jumpscale8/lib/JumpScale/__init__.py
[Wed29 11:21] - InstallTools.py     :1145:installtools                   - INFO     - symlink: src:/opt/code/github/jumpscale/jumpscale_core8/lib/JumpScale/__init__.py dest(islink):/opt/jumpscale8/lib/Jum
pScale/__init__.py
```

Place 2:
```
[Wed29 11:25] - InstallTools.py     :645 :installtools                   - INFO     - None:pull:https://github.com/Jumpscale/ays_jumpscale8.git ->/opt/code/github/jumpscale/ays_jumpscale8
[Wed29 11:25] - InstallTools.py     :683 :installtools                   - INFO     - git pull https://github.com/Jumpscale/ays_jumpscale8.git -> /opt/code/github/jumpscale/ays_jumpscale8
[Wed29 11:25] - InstallTools.py     :688 :installtools                   - INFO     - mkdir -p /opt/code/github/jumpscale/ays_jumpscale8;cd /opt/code/github/jumpscale/ays_jumpscale8;git -c http.sslVerify=false pull origin 8.2.0
Enter passphrase for key '/root/.ssh/id_rsa': 
Enter passphrase for key '/root/.ssh/id_rsa': 
E:From github.com:Jumpscale/ays_jumpscale8
E:* branch            8.2.0      -> FETCH_HEAD
Already up-to-date.
```

**Comment by ashraffouda** [comment]
I traced this issue on a new container and it doesn't exists like described above 

- if you installed js and the repo exists it will continue the installation successfully without any issues

- this problem will **only** appears it the existing repo was cloned with **ssh**. In this case the installer will not change you **git config** by itself 
As conclusion if u already have the repo and this repo was cloned with https the installer will not complain,  if u already have the repo BUT this repo cloned with ssh the installer will complain
