### ISSUE TITLE
ays start Dosn't work after fresh installation of 8.2.0

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/jumpscale_core8#798]
```
root@vm-2582:/opt/code/github/jumpscale/ays_jumpscale8# ays start
[Wed29 13:08] - AtYourServiceFactory.py:39  :j.atyourservice                - INFO     - start ays service, will take 5 sec
[Wed29 13:08] - CuisineTmux.py      :132 :j.cuisinetmux                  - INFO     - reread from tmux, cmd did not start yet

**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 635, in <module>
    cli()
  File "/usr/local/bin/ays", line 556, in start
    j.atyourservice.start(bind=bind, port=port, debug=debug)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceFactory.py", line 48, in start
    rc, out = j.tools.cuisine.local.tmux.executeInScreen(sname, "ays", cmd, reset=True, wait=5)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineTmux.py", line 176, in executeInScreen
    rc, out = checkOutput(die)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineTmux.py", line 161, in checkOutput
    raise j.exceptions.RuntimeError(msg)
JSExceptions.RuntimeError: ERROR: Could not execute cmd:cd /opt/code/github/jumpscale/jumpscale_core8/apps/atyourservice;jspython main.py --host 127.0.0.1 --port 5000
Out/Err:
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from JumpScale import j
ImportError: No module named 'JumpScale'
```
## Note: 
if you log out and log in the tmux session, it will work out

## Version
8.2.0

**Comment by xmonader** [comment]
On a fresh installation that's what I got
```
root@vm-109177:~# js
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from JumpScale import j

In [2]: j.clients.atyourservice

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/bin/js in <module>()
----> 1 j.clients.atyourservice

/opt/jumpscale8/lib/JumpScale/__init__.py in __getattr__(self, attr)
     71         sys.path.append(modpath)
     72         obj0 = importlib.machinery.SourceFileLoader(
---> 73             classname, classfile).load_module()
     74         obj = eval("obj0.%s()" % classname)
     75         sys.path.pop(sys.path.index(modpath))

/usr/lib/python3.5/importlib/_bootstrap_external.py in _check_name_wrapper(self, name, *args, **kwargs)

/usr/lib/python3.5/importlib/_bootstrap_external.py in load_module(self, fullname)

/usr/lib/python3.5/importlib/_bootstrap_external.py in load_module(self, fullname)

/usr/lib/python3.5/importlib/_bootstrap.py in _load_module_shim(self, fullname)

/usr/lib/python3.5/importlib/_bootstrap.py in _load(spec)

/usr/lib/python3.5/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.5/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.5/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/opt/jumpscale8/lib/JumpScale/clients/atyourservice/Factory.py in <module>()
----> 1 from JumpScale.clients.atyourservice.sync_client import Client
      2 from JumpScale import j
      3 
      4 
      5 class Factory:

/opt/jumpscale8/lib/JumpScale/clients/atyourservice/sync_client/__init__.py in <module>()
      1 import requests
      2 
----> 3 from .client import Client as APIClient
      4 
      5 from .oauth2_client_itsyouonline import Oauth2ClientItsyouonline

/opt/jumpscale8/lib/JumpScale/clients/atyourservice/sync_client/client.py in <module>()
      2 
      3 from .ays_service import  AysService
----> 4 from .webhooks_service import  WebhooksService
      5 
      6 

ImportError: No module named 'JumpScale.clients.atyourservice.sync_client.webhooks_service'

```
JumpScale was available, but the error I found was
```
ImportError: No module named 'JumpScale.clients.atyourservice.sync_client.webhooks_service'
```

**Comment by rkhamis** [comment]
Already fixed

**Comment by zaibon** [comment]
Actually I manage to reproduce the exact error that Jhon had.

To reproduce: 
- install jumpscale
- just after do `ays start`
AYS will start in the same tmux as redis. But for some reason the environment in the tmux is not valid and jumpscale can't load.

If I kill tmux and restart, it works properly. So I suspect jumpscale install start redis too fast and the environment for Jumpscale is not properly done yet.

**Comment by xmonader** [comment]
Fixed by https://github.com/Jumpscale/jumpscale_core8/pull/808
