### ISSUE TITLE
Fail in installing JS

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/jumpscale_core8#823]
Can't install js 8.2.0 on our ubuntu 16.04 vms. I did apt-get update and it wasn't help
```bash
Installing collected packages: cython
Successfully installed cython-0.25.2
The directory '/home/cloudscalers/.cache/pip/http' or its parent directory is not owned by the current user and the 
cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you m
ay want sudo's -H flag.
The directory '/home/cloudscalers/.cache/pip' or its parent directory is not owned by the current user and caching w
heels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want
 sudo's -H flag.
Collecting pycapnp
  Downloading pycapnp-0.5.11.tar.gz (454kB)
    100% |████████████████████████████████| 460kB 1.9MB/s 
Installing collected packages: pycapnp
  Running setup.py install for pycapnp ...

Traceback (most recent call last):                                                                   [1743/1834]
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-khe4bs8w/pycapnp/setup.py", line 180, in <module>
        'Topic :: Communications'],
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-khe4bs8w/pycapnp/setup.py", line 124, in run
        build_libcapnp(bundle_dir, build_dir)
      File "/tmp/pip-build-khe4bs8w/pycapnp/buildutils/build.py", line 30, in build_libcapnp
        raise RuntimeError('Make failed')
    RuntimeError: Make failed
    
    ----------------------------------------


    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-khe4bs8w/pycapnp/setup.py';f=g
etattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 
'exec'))" install --record /tmp/pip-h8u6ch2u-record/install-record.txt --single-version-externally-managed --compile
" failed with error code 1 in /tmp/pip-build-khe4bs8w/pycapnp/
Traceback (most recent call last):
  File "bootstrap.py", line 50, in <module>
    do.installer.prepare()
  File "/tmp/InstallTools.py", line 2430, in prepare
    self.do.dependencies.all()
  File "/tmp/dependencies.py", line 48, in all
    self.capnp(executor=executor)
  File "/tmp/dependencies.py", line 68, in capnp
    self.do.pip(["cython", "pycapnp"], executor=executor)
  File "/tmp/InstallTools.py", line 1143, in pip
    self.executeInteractive(cmd)
  File "/tmp/InstallTools.py", line 1757, in executeInteractive
    raise RuntimeError("Could not execute %s" % command)
RuntimeError: Could not execute pip3 install pycapnp --upgrade
```

**Comment by rkhamis** [comment]
The machine didn't meet the minimum requirements
