### ISSUE TITLE
redis oom out of memory crashes ays server

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/jumpscale_core8#865]
```
[Sun30 09:31] - Job.py              :63  :j.jobcontroller.job.9f13b5da965a75a32bbfb4e4d2cb15c6 - INFO     - job job: ardb!mycluster_data_0 (monitor) done sucessfuly
[Sun30 09:31] - Job.py              :63  :j.jobcontroller.job.4d24c9ab7310a9f4f41006228f9a6109 - INFO     - job job: filesystem!cluster_mycluster_vde (update_sizeOnDisk) done sucessfuly
[Sun30 09:31] - Job.py              :63  :j.jobcontroller.job.13ca0d303fd7f11c8a11464408def7ef - INFO     - job job: filesystem!cluster_mycluster_vdb (update_sizeOnDisk) done sucessfuly
[Sun30 09:31] - Job.py              :63  :j.jobcontroller.job.87c87781dd9d971241ea00eb8a758223 - INFO     - job job: container!mycluster_metadata_0 (monitor) done sucessfuly
[Sun30 09:31] - Job.py              :63  :j.jobcontroller.job.46c953ade78a9159d6c5d3eb8cf58f1b - INFO     - job job: ardb!mycluster_metadata_0 (monitor) done sucessfuly
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2694, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 1944, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_61c0bda102201679fa6b937c5bea6be8b32d7fe6): @user_script:22: @user_script: 22: -OOM command not allowed when used memory > 'maxmemory'.

Original exception was:
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48380)
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Job.py", line 65, in _execute_cb
    job.save()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Job.py", line 229, in save
    self.model.save()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/models/JobModel.py", line 141, in save
    self.collection._db.set(self.key, buff, expire=172800)
  File "/opt/jumpscale8/lib/JumpScale/servers/key_value_store/store.py", line 248, in set
    self._set(key, data, expire=expire)
  File "/opt/jumpscale8/lib/JumpScale/servers/key_value_store/redis_store.py", line 37, in _set
    return self.redisclient.set(self._getKey(key), val, ex=expire)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 1072, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: OOM command not allowed when used memory > 'maxmemory'.
```

**Comment by rkhamis** [comment]
@grimpy can you add more information regarding what keys were in redis?

**Comment by grimpy** [comment]
Next time it happens I'll update this ticket :)

**Comment by xmonader** [comment]
Hopefully fixed by this https://github.com/Jumpscale/jumpscale_core8/commit/849a9c124a243d27dbacd76fcf23ccb194b73d4f
